[book]
title = "The Dacite Book"
authors = ["Jonathan Laggett"]
description = "How to think about data and how to build apps with Dacite values and stores."
language = "en"
src = "."

[build]
build-dir = "../../target/site/book"

[output.html]
site-url = "/book/"
git-repository-url = "https://github.com/jclaggett/dacite"
edit-url-template = "https://github.com/jclaggett/dacite/edit/main/docs/book/{path}"
default-theme = "light"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
